version: '3.6'
services:
  elasticsearch:
    image: elasticsearch:7.16.2
    container_name: elasticsearch
    restart: always
    volumes:
      - elastic_data:/usr/share/elasticsearch/data/
    environment:
      ES_JAVA_OPTS: "-Xmx1g -Xms1g"
      discovery.type: single-node
      ELASTIC_PASSWORD: admin
      ELASTICSEARCH_USERNAME: admin
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - elk

  kibana:
    image: kibana:7.16.2
    container_name: kibana
    restart: always
    ports:
      - '5601:5601'
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: admin
      ELASTICSEARCH_PASSWORD: admin
    depends_on:
      - elasticsearch
    networks:
      - elk

  heartbeat:
    image: docker.elastic.co/beats/heartbeat:7.16.1
    container_name: heartbeat
    volumes:
      - ./heartbeat/heartbeat.yml:/usr/share/heartbeat/heartbeat.yml
    depends_on:
      - elasticsearch
    networks:
      - elk

volumes:
  elastic_data: {}

networks:
  elk: